compiler:
  - gcc
  - clang
language: cpp
notifications:
  email: false
script: make
after_success:
  - make check
  - sudo apt-get -qq install valgrind
  - valgrind --leak-check=full --show-reachable=yes bin/thinker
